version: '1.0'
services:
  nginx:
    image: nginx:latest
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf:ro'
    ports:
      - "3000:80"
    links:
      - pwdapi1
      - pwdapi2
    depends_on:
    - pwdapi1
    - pwdapi2

  pwdapi1:
    image: nicopaez/passwordapi-java
  pwdapi2:
    image: nicopaez/passwordapi-java
