version: '1.0'
services:
  pwdapi:
    image: nicopaez/passwordapi-java:latest
    hostname: pwdapi
    expose:
      - "8080"
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - pwdapi
    ports:
      - "4000:4000"
networks:
  default:
    driver: bridge
    name: pwdapi
